baseURL: 'http://strategineer.com/'
languageCode: 'en-us'
title: 'Strategineer'
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true





markup:
 defaultMarkdownHandler: goldmark
 goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

