author:
  name: "Strategineer"

baseURL: 'http://strategineer.com/'
languageCode: 'en-us'
title: 'Strategineer'
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

permalinks:
  posts: /:section/:year-:month-:day


taxonomies:
  blogtag: "blog/tags"
  reviewstag: "reviews/tags"
  cocktailstag: "cocktails/tags"
  foodtag: "food/tags"
  projectstag: "projects/tags"

permalinks:
  blogtags: /blog/tags/:slug/
  reviewstags: /reviews/tags/:slug/
  cocktailstags: /cocktails/tags/:slug/
  foodtags: /food/tags/:slug/
  projectstags: /projects/tags/:slug/

markup:
 defaultMarkdownHandler: goldmark
 goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

