module:
  imports:
  - path: github.com/future-wd/hugo-responsive-images

  
related:
  includeNewer: true
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: series
    pattern: ""
    toLower: false
    type: basic
    weight: 200
  threshold: 80
  toLower: false
  
params:
  authors:
    email: "me@strategineer.com"
    copyright-year: "2024"
    name: "Strategineer"

baseURL: 'https://strategineer.com/'
languageCode: 'en-us'
title: "Strat"
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
timeout: "60s"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

taxonomies:
  "blog post": "blog/tags"
  "review": "reviews/tags"
  "cocktail": "cocktails/tags"
  "recipe": "food/tags"
  "project": "projects/tags"
  "book": "books/tags"
  "author": "authors"

permalinks:
  posts: /:section/:year-:month-:day
  "blog post": /blog/tags/:slug/
  "review": /reviews/tags/:slug/
  "cocktail": /cocktails/tags/:slug/
  "recipe": /food/tags/:slug/
  "project": /projects/tags/:slug/
  "book": /books/tags/:slug/
  "author": /authors/:slug/

imaging:
  quality: 90
  exif:
    disableDate: true
    disableLatLong: true

markup:
 defaultMarkdownHandler: goldmark
 goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

security:
  exec:
    allow:
      - '^dart-sass-embedded$'
      - '^go$'
      - '^npx$'
      - '^postcss$'
      - '^nvim$'

build:
  buildStats:
    enable: true