source 'https://rubygems.org'

gem 'middleman', '~> 4.4'
gem 'middleman-syntax'
gem 'builder', '~> 3.0'
gem 'middleman-autoprefixer'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-robots'
gem 'middleman-graphviz'
gem "middleman-imageoptim", '~> 0.3.0'
gem 'bootstrap'
gem 'tzinfo-data'
