source 'https://rubygems.org'

gem 'middleman', '~> 4.4'
gem 'middleman-syntax'
gem 'builder', '~> 3.0'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-robots'
gem 'middleman-graphviz'
gem "middleman-imageoptim", '~> 0.3.0'
gem 'bootstrap', '~> 4.3'
gem 'tzinfo-data'
