source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-syntax'
gem 'builder', '~> 3.0'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-robots'
gem 'bootstrap', '~> 4.3'
gem 'tzinfo-data'
gem 'mini_racer'
